/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-07-18 02:41:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"utf-8\">\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("	<title>OES | Home</title>\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"></script>\n");
      out.write("	<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\n");
      out.write("	<script src=\"https://use.fontawesome.com/releases/v5.0.8/js/all.js\"></script>\n");
      out.write("        <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/4.5/examples/carousel/\">\n");
      out.write("\n");
      out.write("     <style>\n");
      out.write("      .bd-placeholder-img {\n");
      out.write("        font-size: 1.125rem;\n");
      out.write("        text-anchor: middle;\n");
      out.write("        -webkit-user-select: none;\n");
      out.write("        -moz-user-select: none;\n");
      out.write("        -ms-user-select: none;\n");
      out.write("        user-select: none;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      @media (min-width: 768px) {\n");
      out.write("        .bd-placeholder-img-lg {\n");
      out.write("          font-size: 3.5rem;\n");
      out.write("        }\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"index.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <form id=\"form1\">\n");
      out.write("        <header>\n");
      out.write("            <!--Navigation Bar-->\n");
      out.write("            <nav class=\"navbar navbar-expand-md navbar-dark fixed-top bg-dark\">\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\"><b>ONLINE EXAMINATION SYSTEM</b></a>\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\" aria-controls=\"navbarCollapse\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("                </button>\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\n");
      out.write("                    <ul class=\"navbar-nav ml-auto\">\n");
      out.write("                    <li class=\"nav-item active\">\n");
      out.write("                        <a class=\"nav-link\" href=\"index.jsp\">Home</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link\" href=\"aboutus.jsp\">About</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item dropdown\">\n");
      out.write("		        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"dropdown03\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Login</a>\n");
      out.write("			    <div class=\"dropdown-menu\" aria-labelledby=\"dropdown03\">\n");
      out.write("			        <a class=\"dropdown-item\" href=\"login.jsp\">Student</a>\n");
      out.write("				<a class=\"dropdown-item\" href=\"adminlogin.jsp\">Admin</a>\n");
      out.write("			    </div>\n");
      out.write("		    </li>\n");
      out.write("		    <li class=\"nav-item\">\n");
      out.write("			<a class=\"nav-link\" href=\"register.jsp\">Sign Up</a>\n");
      out.write("		    </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <!--Image Carousel-->\n");
      out.write("	<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\n");
      out.write("            <ol class=\"carousel-indicators\">\n");
      out.write("            <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("            <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\n");
      out.write("            <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\n");
      out.write("        </ol>\n");
      out.write("        <div class=\"carousel-inner\">\n");
      out.write("        <div class=\"carousel-item active\">\n");
      out.write("            <svg class=\"bd-placeholder-img\" width=\"100%\" height=\"100%\" xmlns=\"http://www.w3.org/2000/svg\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\" role=\"img\"><rect width=\"100%\" height=\"100%\" fill=\"#777\"/></svg>\n");
      out.write("            <img src=\"CarouselBG.png\" />\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"carousel-caption text-left\">\n");
      out.write("            <h1><b>Easy to Use.</b></h1>\n");
      out.write("            <p>A Simple and Easy to use Online Examination tool for Colleges and Universities.</p>\n");
      out.write("            <p><a class=\"btn btn-lg btn-primary\" href=\"register.jsp\" role=\"button\">Sign Up</a></p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"carousel-item\">\n");
      out.write("        <svg class=\"bd-placeholder-img\" width=\"100%\" height=\"100%\" xmlns=\"http://www.w3.org/2000/svg\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\" role=\"img\"><rect width=\"100%\" height=\"100%\" fill=\"#777\"/></svg>\n");
      out.write("          <img src=\"CarouselBG.png\" />\n");
      out.write("          <div class=\"container\">\n");
      out.write("          <div class=\"carousel-caption\">\n");
      out.write("            <h1><b>Efficient and Reliable.</b></h1>\n");
      out.write("            <p>An Efficient and a Reliable tool to conduct Online Examinations.</p>\n");
      out.write("            <p><a class=\"btn btn-lg btn-primary\" href=\"about.jsp\" role=\"button\">Learn more</a></p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"carousel-item\">\n");
      out.write("        <svg class=\"bd-placeholder-img\" width=\"100%\" height=\"100%\" xmlns=\"http://www.w3.org/2000/svg\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\" role=\"img\"><rect width=\"100%\" height=\"100%\" fill=\"#777\"/></svg>\n");
      out.write("          <img src=\"CarouselBG.png\" />\n");
      out.write("          <div class=\"container\">\n");
      out.write("          <div class=\"carousel-caption text-right\">\n");
      out.write("            <h1><b>Simple and Non-Complex.</b></h1>\n");
      out.write("            <p>A Clean and an Elegant User Interface with Minimal Complexities.</p>\n");
      out.write("            <p><a class=\"btn btn-lg btn-primary\" href=\"login.jsp\" role=\"button\">Start Exam</a></p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <a class=\"carousel-control-prev\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">\n");
      out.write("      <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("      <span class=\"sr-only\">Previous</span>\n");
      out.write("    </a>\n");
      out.write("    <a class=\"carousel-control-next\" href=\"#myCarousel\" role=\"button\" data-slide=\"next\">\n");
      out.write("      <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("      <span class=\"sr-only\">Next</span>\n");
      out.write("    </a>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("    <!--Jumbotron-->\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("    <div class=\"row jumbotron\">\n");
      out.write("        <div class=\"col-xs-12 col-sm-12 col-md-9 col-lg-9 col-xl-10\">\n");
      out.write("            <p class=\"lead\">An Online Examination System for Colleges and Universities to schedule their exams.\n");
      out.write("                If your organization faces any challenges while conducting the exams or your organization has any concerns regarding the system please contact us. \n");
      out.write("            </p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("    <!--Build with Ease and Logos section-->\n");
      out.write("    <div class=\"container-fluid padding\">\n");
      out.write("    <div class=\"row welcome text-center\">\n");
      out.write("        <div class=\"col-12\">\n");
      out.write("            <h1 class=\"display-4\">Assess with ease.</h1>\n");
      out.write("        </div>\n");
      out.write("        <hr />\n");
      out.write("        <div class=\"col-12\">\n");
      out.write("            <p class=\"lead\">\n");
      out.write("                An Online Examination Tool that allows for the swift, efficient and smooth conduction of college and university exams.\n");
      out.write("            </p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("    <div class=\"row text-center padding\">\n");
      out.write("        <div class=\"col-xs-12 col-sm-6 col-md-4\">\n");
      out.write("            <i class=\"fa fa-bolt\" aria-hidden=\"true\"></i>\n");
      out.write("            <h3>Fast</h3>\n");
      out.write("            <p>Fast and Smooth Assessment.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-xs-12 col-sm-6 col-md-4\">\n");
      out.write("            <i class=\"fa fa-lock\" aria-hidden=\"true\"></i>\n");
      out.write("            <h3>Secure</h3>\n");
      out.write("            <p>Secure Examination Process.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-sm-12 col-md-4\">\n");
      out.write("            <i class=\"fa fa-check-square\" aria-hidden=\"true\"></i>\n");
      out.write("            <h3>Reliable</h3>\n");
      out.write("            <p>Reliable and Trustworthy Platform</p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <hr class=\"my-4\"/>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!--Connect Section-->\n");
      out.write("    <div class=\"container-fluid padding\">\n");
      out.write("    <div class=\"row text-center padding\">\n");
      out.write("        <div class=\"col-12\">\n");
      out.write("            <h2>Connect</h2>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-12 social padding\">\n");
      out.write("            <a href=\"https://www.facebook.com/\"><i class=\"fab fa-facebook\"></i></a>\n");
      out.write("            <a href=\"https://www.youtube.com/\"><i class=\"fab fa-youtube\"></i></a>\n");
      out.write("            <a href=\"https://www.instagram.com/\"><i class=\"fab fa-instagram\"></i></a>\n");
      out.write("            <a href=\"https://myaccount.google.com/intro/personal-info\"><i class=\"fab fa-google-plus-g\"></i></a>\n");
      out.write("            <a href=\"https://twitter.com/\"><i class=\"fab fa-twitter\"></i></a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("    <!--Footer-->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("   </form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
