/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-07-18 02:46:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.3.1/css/all.css\" integrity=\"sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU\" crossorigin=\"anonymous\">\n");
      out.write("        \n");
      out.write("        <title>OES | Login</title>\n");
      out.write("        <style>\n");
      out.write("           #logreg-forms{\n");
      out.write("    width:412px;\n");
      out.write("    margin:10vh auto;\n");
      out.write("    background-color:#f3f3f3;\n");
      out.write("    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);\n");
      out.write("    transition: all 0.3s cubic-bezier(.25,.8,.25,1);\n");
      out.write("}\n");
      out.write("#logreg-forms form {\n");
      out.write("    width: 100%;\n");
      out.write("    max-width: 410px;\n");
      out.write("    padding: 15px;\n");
      out.write("    margin: auto;\n");
      out.write("}\n");
      out.write("#logreg-forms .form-control {\n");
      out.write("    position: relative;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    height: auto;\n");
      out.write("    padding: 10px;\n");
      out.write("    font-size: 16px;\n");
      out.write("}\n");
      out.write("#logreg-forms .form-control:focus { z-index: 2; }\n");
      out.write("#logreg-forms .form-signin input[type=\"text\"] {\n");
      out.write("    margin-bottom: -1px;\n");
      out.write("    border-bottom-right-radius: 0;\n");
      out.write("    border-bottom-left-radius: 0;\n");
      out.write("    \n");
      out.write("}\n");
      out.write("#logreg-forms .form-signin input[type=\"password\"] {\n");
      out.write("    border-top-left-radius: 0;\n");
      out.write("    border-top-right-radius: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#logreg-forms a{\n");
      out.write("    display: block;\n");
      out.write("    padding-top:10px;\n");
      out.write("    color:grey;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("#logreg-forms input[type=\"submit\"]{ margin-top:10px;  background-color: #4a4747}\n");
      out.write("\n");
      out.write("#logreg-forms .form-reset, #logreg-forms .form-signup{ display: none; }\n");
      out.write("\n");
      out.write("#logreg-forms .form-signup input { margin-bottom: 2px;}\n");
      out.write("\n");
      out.write("/* Mobile */\n");
      out.write("\n");
      out.write("@media screen and (max-width:500px){\n");
      out.write("    #logreg-forms{\n");
      out.write("        width:300px;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("}\n");
      out.write("\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div id=\"logreg-forms\">\n");
      out.write("        <form class=\"form-signin\" action=\"login\" method=\"GET\">\n");
      out.write("            <h1 class=\"h3 mb-3 font-weight-normal\" style=\"text-align: center\">Login</h1>\n");
      out.write("            <hr/>\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Username\" required=\"\" autofocus=\"\" name=\"email\" />\n");
      out.write("            <input type=\"password\" class=\"form-control\" placeholder=\"Password\" required=\"\" name=\"pass\" /><br>\n");
      out.write("            \n");
      out.write("            <input class=\"btn btn-success btn-block\" type=\"submit\" value=\"Login\" style=\"color:white;\"><br/>\n");
      out.write("            <a href=\"register.jsp\" id=\"forgot_pswd\">Don't have an account? Sign Up</a><br/>\n");
      out.write("            <h5 style=\"color:red; text-align: center;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${err}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\n");
      out.write("            <hr/>\n");
      out.write("        </form>\n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
