/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-06-18 05:10:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.SignUpBean;
import dao.ProfileDao;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


String email;
SignUpBean b;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1655197463993L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.SignUpBean");
    _jspx_imports_classes.add("dao.ProfileDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>MyProfile</title>\r\n");
      out.write("<link href=\"utilities.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("body\r\n");
      out.write("{\r\n");
      out.write("padding:0px;\r\n");
      out.write("}\r\n");
      out.write("aside\r\n");
      out.write("{\r\n");
      out.write("    width:30%;\r\n");
      out.write("    height:80vh;\r\n");
      out.write("    display:inline-block;\r\n");
      out.write("    box-shadow: 0px 0px 3px #aaa;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    padding:20px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    margin:10px 20px;\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    top:100px;\r\n");
      out.write("}\r\n");
      out.write(".profile-details\r\n");
      out.write("{\r\n");
      out.write("    /* background-color: aqua; */\r\n");
      out.write("    color:rgb(250, 126, 147);\r\n");
      out.write("    display: block;\r\n");
      out.write("    width:60%;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    margin:auto;\r\n");
      out.write("    padding:10px;\r\n");
      out.write("}\r\n");
      out.write("#profile-pic\r\n");
      out.write("{\r\n");
      out.write("    height:150px;\r\n");
      out.write("    width:150px;\r\n");
      out.write("    border-radius: 30px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin:auto;\r\n");
      out.write("    box-shadow: 0px 0px 3px black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("main\r\n");
      out.write("{\r\n");
      out.write("    width:60%;\r\n");
      out.write("    height: 80vh;;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    box-shadow: 0px 0px 3px #aaa;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    padding:20px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    top:110px;\r\n");
      out.write("    left:33%;\r\n");
      out.write("}\r\n");
      out.write("legend{\r\n");
      out.write("    color:rgb(250, 91, 117);\r\n");
      out.write("    font-size:20px;\r\n");
      out.write("}\r\n");
      out.write("fieldset\r\n");
      out.write("{\r\n");
      out.write("	border:none;\r\n");
      out.write("    box-shadow:0px 0px 3px #aaa;\r\n");
      out.write("    margin:10px 20px;\r\n");
      out.write("    padding:20px;\r\n");
      out.write("}\r\n");
      out.write("input{\r\n");
      out.write("    width:60%;\r\n");
      out.write("    height: 26px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin:auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

email=(String)session.getAttribute("email"); 
if(session.getAttribute("user").equals("Admin"))
	b=ProfileDao.fetchAdminData(email);
else
	b=ProfileDao.fetchBuyerData(email);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Prompt&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#header {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-color: rgb(255, 255, 255);\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#name-wrapper {\r\n");
      out.write("	width: 10%;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#name {\r\n");
      out.write("	color: black;\r\n");
      out.write("	padding: 4px;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("	font-size: 35px;\r\n");
      out.write("	font-family: 'Prompt', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbar {\r\n");
      out.write("	background-color: antiquewhite;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	height: 38px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item {\r\n");
      out.write("	padding: 0px 5px;\r\n");
      out.write("	margin: 5px 10px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	top: 8px;\r\n");
      out.write("}\r\n");
      out.write("#signup {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<link href=\"utilities.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header id=\"header\">\r\n");
      out.write("	<div id=\"name-wrapper\">\r\n");
      out.write("		<!-- <span><img id=\"logo\" src=\"logo4.png\"></span> -->\r\n");
      out.write("		<span id=\"name\">ELLA</span>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"navbar-wrapper\">\r\n");
      out.write("		<nav id=\"navbar\">\r\n");
      out.write("		 <span id=\"menu-item1\"><a class=\"menu-item link\" href=\"index.jsp\">Home</a></span>\r\n");
      out.write("		 <span id=\"menu-item2\"><a class=\"menu-item link\" href=\"#\">Blog</a></span>\r\n");
      out.write("		 <span id=\"menu-item3\"><a class=\"menu-item link\" href=\"shop.jsp\">Shop</a></span> \r\n");
      out.write("		 <span id=\"menu-item4\"><a class=\"menu-item link\" href=\"#\">About</a></span>\r\n");
      out.write("		 <span id=\"menu-item5\"><a class=\"menu-item link\" href=\"contact.jsp\">Contact</a></span>\r\n");
      out.write("		<!-- <span><a class=\"menu-item\" id=\"signup\" href=\"#\">Sign In</a></span> --> </nav>\r\n");
      out.write("	</div>\r\n");
      out.write("	</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "dp.jsp", out, false);
      out.write("\r\n");
      out.write("<aside>\r\n");
      out.write("        <img id=\"profile-pic\" src=\"");
      out.print( b.getDp());
      out.write(" \">\r\n");
      out.write("        <span class=\"profile-details\">");
      out.print(b.getUsername() );
      out.write("</span>\r\n");
      out.write("        <span class=\"profile-details\">");
      out.print(b.getFname()+" "+b.getLname() );
      out.write("</span>\r\n");
      out.write("        ");

        if(session.getAttribute("user").equals("admin"))
        	{
       		
      out.write("\r\n");
      out.write("       		<span class=\"profile-details\">");
      out.print(b.getId() );
      out.write("</span>\r\n");
      out.write("       		");

       		}
       	
      out.write("\r\n");
      out.write("        <span class=\"profile-details\">");
      out.print(b.getEmail() );
      out.write("</span>\r\n");
      out.write("    </aside>\r\n");
      out.write("    <main>\r\n");
      out.write("        \r\n");
      out.write("            <form action=\"update.jsp\" method=\"post\">\r\n");
      out.write("                <fieldset>\r\n");
      out.write("                    <legend>General</legend>\r\n");
      out.write("                    <input class=\"input inputs\" type=\"text\" name=\"username\" value=\"");
      out.print( b.getUsername());
      out.write(" \" placeholder=\"Username\"><br>\r\n");
      out.write("                    <input class=\"input inputs\" type=\"text\" name=\"fname\" value=\"");
      out.print( b.getFname());
      out.write("\" placeholder=\"First name\"><br>\r\n");
      out.write("                    <input class=\"input inputs\" type=\"text\" name=\"lname\" value=\"");
      out.print( b.getLname());
      out.write("\" placeholder=\"Last name\"><br>\r\n");
      out.write("                </fieldset>\r\n");
      out.write("            \r\n");
      out.write("                <fieldset>\r\n");
      out.write("                    <legend>Contact</legend>\r\n");
      out.write("                    <input class=\"input inputs\" type=\"text\" name=\"mobile\" value=\"");
      out.print( b.getMobile());
      out.write("\" placeholder=\"Mobile\"><br>\r\n");
      out.write("                    <input disabled class=\"input inputs\" type=\"text\" name=\"email\" value=\"");
      out.print( b.getEmail());
      out.write("\" placeholder=\"Email\"><br>\r\n");
      out.write("                </fieldset>\r\n");
      out.write("                <fieldset>\r\n");
      out.write("                    <legend>Security</legend>\r\n");
      out.write("                    <input class=\"input inputs\" type=\"password\" name=\"pwd\" value=\"");
      out.print( b.getPwd());
      out.write("\" placeholder=\"Password\"><br>\r\n");
      out.write("                </fieldset><br>\r\n");
      out.write("                 <input class=\"input buttons\" type=\"submit\" value=\"Save Changes\">\r\n");
      out.write("            </form>\r\n");
      out.write("    </main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
