/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-06-11 03:40:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.SignUpDao;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.SignUpDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Sign Up</title>\r\n");
      out.write("<link href=\"utilities.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("body\r\n");
      out.write("{\r\n");
      out.write("    background-image: url('register.webp');\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top:200px;\r\n");
      out.write("    right:200px;\r\n");
      out.write("    width:30%;\r\n");
      out.write("    height: 340px;\r\n");
      out.write("}\r\n");
      out.write(".item\r\n");
      out.write("{\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin:8px;\r\n");
      out.write("    width:70%;\r\n");
      out.write("    height:20px;\r\n");
      out.write("}\r\n");
      out.write(".input\r\n");
      out.write("{\r\n");
      out.write("    margin:5px;\r\n");
      out.write("    width:90%;\r\n");
      out.write("}\r\n");
      out.write("#signup\r\n");
      out.write("{\r\n");
      out.write("    width:90%;\r\n");
      out.write("    margin: 5px;\r\n");
      out.write("}\r\n");
      out.write("#signup:hover\r\n");
      out.write("{\r\n");
      out.write("    background-color:rgb(226, 9, 74) ;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"\" method=\"post\" class=\"forms\">\r\n");
      out.write("        <span class=\"item\">\r\n");
      out.write("            <input type=\"radio\" name=\"user\" value=\"Admin\">\r\n");
      out.write("            <span class=\"itemx\">Admin</span>\r\n");
      out.write("        </span><br>\r\n");
      out.write("        <span class=\"item\">\r\n");
      out.write("            <input type=\"radio\" name=\"user\" value=\"Buyer\">\r\n");
      out.write("            <span class=\"itemx\">Buyer</span>\r\n");
      out.write("        </span><br>\r\n");
      out.write("        <input class=\"input inputs\" type=\"text\" name=\"username\" placeholder=\"enter username\"><br>\r\n");
      out.write("        <input class=\"input inputs\" type=\"text\" name=\"fname\" placeholder=\"enter first name\"><br>\r\n");
      out.write("        <input class=\"input inputs\" type=\"text\" name=\"lname\" placeholder=\"enter last name\"><br>\r\n");
      out.write("        <input class=\"input inputs\" type=\"text\" name=\"email\" placeholder=\"enter your email\"><br>\r\n");
      out.write("        <input class=\"input inputs\" type=\"text\" name=\"mobile\" placeholder=\"enter your mobile no.\"><br>\r\n");
      out.write("        <input class=\"input inputs\" type=\"password\" name=\"pwd\" placeholder=\"enter password\"><br>\r\n");
      out.write("        <input class=\"input inputs\" type=\"password\" name=\"pwd\" placeholder=\"confirm password\"><br>\r\n");
      out.write("        <input id=\"signup\" class=\"buttons\" type=\"submit\" value=\"SignUp\"><br>\r\n");
      out.write("    </form>\r\n");
      out.write("    ");
      bean.SignUpBean signupBean = null;
      signupBean = (bean.SignUpBean) _jspx_page_context.getAttribute("signupBean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (signupBean == null){
        signupBean = new bean.SignUpBean();
        _jspx_page_context.setAttribute("signupBean", signupBean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("signupBean"), request);
      out.write("\r\n");
      out.write("    ");

    if(signupBean.getUsername()!=null)
    {
    	boolean isRegistered=false;
    	if(signupBean.getUser().equals("Admin"))
    		isRegistered=SignUpDao.registerAdmin(signupBean);
    	else
    		isRegistered=SignUpDao.registerBuyer(signupBean);
    	
    	if(isRegistered)
    	response.sendRedirect("index.jsp");
    }
    
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
